apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    app: myapp
    type: frontend
spec:
  template:
    metadata:
      name: nginx
      labels:
        app: myapp-pod
        type: frontend
    spec:
      containers:
        - name: nginx
          image: nginx:latest
      
  replicas: 2
